name: Codecov

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  coverage:
    name: Code Coverage • Julia 1 • ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Julia
        uses: julia-actions/setup-julia@v3
        with:
          version: '1'

      - name: Cache Julia artifacts
        uses: julia-actions/cache@v3

      - name: Generate coverage
        run: julia --project=. -e 'using Pkg; Pkg.test(coverage=true)'

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          flags: unittests
